tasks:
  - init: cd /tmp && go get github.com/spf13/cobra/cobra && curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0 && cd - && go get ./... && go build ./... && go test ./... -cover && golangci-lint run
    command: 'echo "TODO: Replace with command to start project"'
